/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#include <tcMenu.h>
#include "Hydroduino_menu.h"

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "Hydroduino", "9dd5e852-8a0d-4d8d-a62f-49a5c344687a" };

LiquidCrystal lcd(0, 1, 2, 4, 5, 6, 7);
LiquidCrystalRenderer renderer(lcd, 20, 4);

// Global Menu Item declarations
RENDERING_CALLBACK_NAME_INVOKE(fnSystemRtCall, backSubItemRenderFn, "System", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoSystem = { "System", 4, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackSystem(fnSystemRtCall, NULL);
SubMenuItem menuSystem(&minfoSystem, &menuBackSystem, NULL);
RENDERING_CALLBACK_NAME_INVOKE(fnCropsRtCall, backSubItemRenderFn, "Crops", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoCrops = { "Crops", 3, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackCrops(fnCropsRtCall, NULL);
SubMenuItem menuCrops(&minfoCrops, &menuBackCrops, &menuSystem);
RENDERING_CALLBACK_NAME_INVOKE(fnSensorsRtCall, backSubItemRenderFn, "Sensors", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoSensors = { "Sensors", 2, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackSensors(fnSensorsRtCall, NULL);
SubMenuItem menuSensors(&minfoSensors, &menuBackSensors, &menuCrops);
extern const char* ActuatorsList;
RENDERING_CALLBACK_NAME_INVOKE(fnConfiguredRtCall, enumItemRenderFn, "Configured", -1, NO_CALLBACK)
ScrollChoiceMenuItem menuConfigured(5, fnConfiguredRtCall, 0, ActuatorsList, 2, 16, NULL);
RENDERING_CALLBACK_NAME_INVOKE(fnActuatorsRtCall, backSubItemRenderFn, "Actuators", -1, NO_CALLBACK)
const PROGMEM SubMenuInfo minfoActuators = { "Actuators", 1, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackActuators(fnActuatorsRtCall, &menuConfigured);
SubMenuItem menuActuators(&minfoActuators, &menuBackActuators, &menuSensors);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).

    // Code generated by plugins.
    Wire.begin();
    lcd.setIoAbstraction(ioFrom8574(0x20, 0xff, &Wire));
    lcd.begin(20, 4);
    renderer.setUpdatesPerSecond(2);
    lcd.configureBacklightPin(3);
    lcd.backlight();
    switches.init(internalDigitalIo(), SWITCHES_POLL_EVERYTHING, true);
    menuMgr.initForUpDownOk(&renderer, &menuActuators, 3, 2, -1);
    menuMgr.setBackButton(4);
    menuMgr.setNextButton(5);
}

