/*  Hydruino: Simple automation controller for hydroponic grow systems.
    Copyright (C) 2022 NachtRaveVL          <nachtravevl@gmail.com>
    Hydroponics Strings
*/

#ifndef HydroponicsStrings_H
#define HydroponicsStrings_H

// Strings Enumeration Table
enum Hydroponics_String {
    HS_ColonSpace,
    HS_Count,
    HS_DoubleSpace,
    HS_csv,
    HS_dat,
    HS_Disabled,
    HS_txt,
    HS_Undefined,
    HS_null,

    HS_Err_AllocationFailure,
    HS_Err_AlreadyInitialized,
    HS_Err_AssertionFailure,
    HS_Err_ExportFailure,
    HS_Err_ImportFailure,
    HS_Err_InitializationFailure,
    HS_Err_InvalidParameter,
    HS_Err_InvalidPinOrType,
    HS_Err_MeasurementFailure,
    HS_Err_MissingLinkage,
    HS_Err_NoPositionsAvailable,
    HS_Err_NotYetInitialized,
    HS_Err_OperationFailure,
    HS_Err_UnsupportedOperation,

    HS_Log_AirReport,
    HS_Log_CalculatedPumping,
    HS_Log_FeedingSequence,
    HS_Log_HasBegan,
    HS_Log_HasDisabled,
    HS_Log_HasEnabled,
    HS_Log_HasEnded,
    HS_Log_LightingSequence,
    HS_Log_MeasuredPumping,
    HS_Log_PreFeedBalancing,
    HS_Log_PreFeedTopOff,
    HS_Log_PreLightSpraying,
    HS_Log_SystemDataSaved,
    HS_Log_SystemUptime,

    HS_Log_Field_pH_Setpoint,
    HS_Log_Field_TDS_Setpoint,
    HS_Log_Field_Temp_Setpoint,
    HS_Log_Field_CO2_Setpoint,
    HS_Log_Field_Time_Calculated,
    HS_Log_Field_Vol_Calculated,
    HS_Log_Field_pH_Measured,
    HS_Log_Field_TDS_Measured,
    HS_Log_Field_Temp_Measured,
    HS_Log_Field_CO2_Measured,
    HS_Log_Field_Time_Measured,
    HS_Log_Field_Vol_Measured,
    HS_Log_Field_Time_Start,
    HS_Log_Field_Time_Finish,

    HS_Key_ActiveLow,
    HS_Key_AdditiveName,
    HS_Key_AirReportInterval,
    HS_Key_AirTempRange,
    HS_Key_AirTemperatureSensor,
    HS_Key_AlwaysFilled,
    HS_Key_AutosaveEnabled,
    HS_Key_AutosaveInterval,
    HS_Key_BaseFeedMultiplier,
    HS_Key_CO2Levels,
    HS_Key_CO2Sensor,
    HS_Key_CalibUnits,
    HS_Key_ComputeHeatIndex,
    HS_Key_ContFlowRate,
    HS_Key_ContPowerUsage,
    HS_Key_CropName,
    HS_Key_CropType,
    HS_Key_CtrlInMode,
    HS_Key_DHTType,
    HS_Key_DailyLightHours,
    HS_Key_DataFilePrefix,
    HS_Key_DetriggerTol,
    HS_Key_DispOutMode,
    HS_Key_EmptyTrigger,
    HS_Key_FeedReservoir,
    HS_Key_FeedTimingMins,
    HS_Key_FeedingTrigger,
    HS_Key_FeedingWeight,
    HS_Key_FilledTrigger,
    HS_Key_Flags,
    HS_Key_FlowRateSensor,
    HS_Key_FlowRateUnits,
    HS_Key_Id,
    HS_Key_InputBitRes,
    HS_Key_InputInversion,
    HS_Key_InputPin,
    HS_Key_Invasive,
    HS_Key_Large,
    HS_Key_LastChangeDate,
    HS_Key_LastFeedingDate,
    HS_Key_LastPruningDate,
    HS_Key_LifeCycleWeeks,
    HS_Key_LimitTrigger,
    HS_Key_LogFilePrefix,
    HS_Key_LogLevel,
    HS_Key_LogToSDCard,
    HS_Key_Logger,
    HS_Key_MaxActiveAtOnce,
    HS_Key_MaxPower,
    HS_Key_MaxVolume,
    HS_Key_Max,
    HS_Key_MeasureMode,
    HS_Key_MeasurementRow,
    HS_Key_MeasurementUnits,
    HS_Key_Min,
    HS_Key_MoistureSensor,
    HS_Key_MoistureUnits,
    HS_Key_Multiplier,
    HS_Key_NightlyFeedRate,
    HS_Key_NumFeedingsToday,
    HS_Key_Offset,
    HS_Key_OutputBitRes,
    HS_Key_OutputPin,
    HS_Key_OutputReservoir,
    HS_Key_PHRange,
    HS_Key_PHSensor,
    HS_Key_Perennial,
    HS_Key_PhaseDurationWeeks,
    HS_Key_PollingInterval,
    HS_Key_PowerSensor,
    HS_Key_PowerUnits,
    HS_Key_PreFeedAeratorMins,
    HS_Key_PreLightSprayMins,
    HS_Key_Pruning,
    HS_Key_PublishToSDCard,
    HS_Key_Publisher,
    HS_Key_PullupPin,
    HS_Key_RailName,
    HS_Key_ReservoirName,
    HS_Key_ReservoirType,
    HS_Key_Revision,
    HS_Key_Scheduler,
    HS_Key_SensorName,
    HS_Key_SowDate,
    HS_Key_Spraying,
    HS_Key_State,
    HS_Key_StdDosingRates,
    HS_Key_SubstrateType,
    HS_Key_SystemMode,
    HS_Key_SystemName,
    HS_Key_TDSRange,
    HS_Key_TDSSensor,
    HS_Key_TDSUnits,
    HS_Key_TemperatureSensor,
    HS_Key_TempUnits,
    HS_Key_TimeZoneOffset,
    HS_Key_Timestamp,
    HS_Key_ToleranceHigh,
    HS_Key_ToleranceLow,
    HS_Key_ToleranceUnits,
    HS_Key_Tolerance,
    HS_Key_TotalFeedingsDay,
    HS_Key_TotalGrowWeeks,
    HS_Key_Toxic,
    HS_Key_TriggerBelow,
    HS_Key_TriggerOutside,
    HS_Key_Type,
    HS_Key_Units,
    HS_Key_UsingISR,
    HS_Key_Value,
    HS_Key_Version,
    HS_Key_Viner,
    HS_Key_VolumeSensor,
    HS_Key_VolumeUnits,
    HS_Key_WaterTemperatureRange,
    HS_Key_WaterTemperatureSensor,
    HS_Key_WeeklyDosingRates,
    HS_Key_WiFiPasswordSeed,
    HS_Key_WiFiPassword,
    HS_Key_WiFiSSID,
    HS_Key_WireDevAddress,
    HS_Key_WirePosIndex,

    Hydroponics_Strings_Count
};

// Returns memory resident string from PROGMEM (Flash) string enumeration.
extern String stringFromPGM(Hydroponics_String strNum);
#define SFP(strNum) stringFromPGM((strNum))

// Makes Strings lookup go through EEPROM, with specified data begin address.
extern void beginStringsFromEEPROM(uint16_t dataAddress);

// Makes Strings lookup go through SD Card strings file at file prefix.
extern void beginStringsFromSDCard(String dataFilePrefix);

#endif // /ifndef HydroponicsStrings_H
